### ISSUE TITLE
/genel sayfası için verilerin hesaplanma formülü

### ISSUE THREAD

**Issue by samilkahraman** [samilkahraman/dikelim#18]
GÜNLÜK OKSİJEN ÜRETİMİMİZ ve CO2 - O2 DÖNÜŞÜMÜ
verileri için ağaç sayısına bağlı hesaplama formüllerinin hazırlanması gerekiyor.

**Comment by ybasesme** [comment]
1 hektar çam ormanı yılda 30 ton oksijen üretir
1 hektar alana 1000 fidan dikileceğini varsayarak
1000 fidan yılda 30 ton O2 üretiyor.
1 fidan yılda 0.03 ton O2 üretir.
1 fidan günde 0.00008219178 ton oksijen = 0.072098052631579 litre oksijen üretir


40 kişinin bir saatte havaya verdiği karbondioksiti yetişkin bir çam ağacı 1 saatte oksijene dönüştürür.
Yetişkin bir çam ağacı günde 40 kişinin havaya verdiği CO2 yi O2 ye dönüştürür.
Normal bir insan 1 günde 30 litre CO2 veriyor.
Yani yetişkin 1 çam ağacı günde yaklaşık 1200 litre CO2 dönüşümü yapar.
